version: '3.8'

services:
  influxdb:
    image: bitnami/influxdb:1.8.5
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=false
      - INFLUXDB_INIT_DATABASE=myk6db
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=bitnami123
      - INFLUXDB_USER=myuser
      - INFLUXDB_PASSWORD=mypassword

  grafana:
    image: bitnami/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"

  k6:
    image: loadimpact/k6:latest
    container_name: k6
    volumes:
      - ./scripts:/scripts
    entrypoint: [ "sleep", "infinity" ]
#    entrypoint: ["k6", "run"]
#    command: ["/scripts/enqueue.js"]