spring:
  config:
    activate:
      on-profile: container
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
  sql:
    init:
      mode: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9105/eureka/
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: info

slack:
  token: 토큰
  channel: '#spring'