spring:
  datasource:
    url: jdbc:mysql://localhost:3306/concert
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: myuser
    password: myuser
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE

