concert-service:
  url: http://localhost:9101/api/concert
member-service:
  url: http://localhost:9100/api/member
reservation-service:
  url: http://localhost:9104/api/reserve
pay-service:
  url: http://localhost:9103/api/pay
queue-service:
  url: http://localhost:9102/api/queue

spring:
  application:
    name: member-service
  datasource:
    url: jdbc:mysql://localhost:3306/member?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: myuser
    password: myuser
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    producer:
      bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      enable-auto-commit: false
      group-id: group_1
    listener:
      ack-mode: manual

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: info

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9105/eureka/
    fetch-registry: true
    register-with-eureka: true

slack:
  token: 토큰
  channel: '#spring'
server:
  port: 9100

