version: '3.8'

services:
  influxdb:
    image: bitnami/influxdb:1.8.5
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=false
      - INFLUXDB_INIT_DATABASE=myk6db
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=bitnami123
      - INFLUXDB_USER=myuser
      - INFLUXDB_PASSWORD=mypassword

  #  prometheus:
  #    image: prom/prometheus
  #    container_name: prometheus
  #    volumes:
  #      - ./prometheus.yml:/prometheus/prometheus.yml:ro
  #    ports:
  #      - "9090:9090"
  #    command:
  #      - "--web.enable-lifecycle"

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./grafana-volume:/var/lib/grafana
    ports:
      - "3200:3000"

