spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reservation?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: myuser
    password: myuser
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    producer:
      bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      enable-auto-commit: false
      group-id: group_1
    listener:
      ack-mode: manual

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: info

slack:
  token: 토큰
  channel: '#spring'
server:
  port: 9094

