concert-service:
  url: http://localhost:9101/api/concert
member-service:
  url: http://localhost:9100/api/member
reservation-service:
  url: http://localhost:9104/api/reserve
pay-service:
  url: http://localhost:9103/api/pay
queue-service:
  url: http://localhost:9102/api/queue

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/concert?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: myuser
    password: myuser
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: info

slack:
  token: 토큰
  channel: '#spring'
server:
  port: 9101

